### ISSUE TITLE
Middleware Crypto can't be used in Next 12

### ISSUE THREAD

**Issue by rosman83** [vvo/iron-session#508] opened 2022-05-10 03:01 UTC
Whenever I'm using the pinned solution for decrypting the cookie in Next JS like so in `_middleware.ts`

```
import Crypto from "crypto";

Crypto.timingSafeEqual = function timingSafeEqual(a, b) {
  if (!Buffer.isBuffer(a) || !Buffer.isBuffer(b) || a.length !== b.length) {
    throw new TypeError("Error in cryptography verification.");
  }
  var out = 0;
  var i = -1;
  while (++i < a.length) out |= a[i] ^ b[i];
  return out === 0;
};
```

I receive this error from Next,

```
error - ./node_modules/@hapi/cryptiles/lib/index.js:3:0
Module not found: Can't resolve 'crypto'

Import trace for requested module:
./node_modules/@hapi/iron/lib/index.js
./node_modules/iron-session/dist/index.mjs
./src/pages/_middleware.ts

https://nextjs.org/docs/messages/module-not-found

You're using a Node.js module (crypto) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
```

**Comment by brc-dd** [comment] 2022-05-14 19:21
Duplicate of #419

**Closed** 2022-08-25 21:21 UTC

**Comment by 4D5A90** [comment] 2022-11-21 18:00
same
