### ISSUE TITLE
Request Context Enhancement - Ability to Access Decrypted Session Data

### ISSUE THREAD

**Issue by younes-alouani** [vvo/iron-session#590] opened 2023-05-11 16:49 UTC
**Description:**

I have been using the iron-session library for session management in my Next.js application. I have created a middleware function to check if the user is authenticated or not. Here's the code for the middleware:

```
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { getIronSession } from "iron-session/edge";
import { sessionOptions } from "./utils/auth/config";
import { LOGIN_PAGE } from "./paths";

export const middleware = async (req: NextRequest) => {
  const res = NextResponse.next();
  const session = await getIronSession(req, res, sessionOptions);
  const { user } = session;
  console.log("from middleware ", user ? user.id : "No user found");
  if (user) {
    return res;
  } else {
    return NextResponse.redirect(new URL(LOGIN_PAGE, req.url), {
      status: 307, // Temporary redirect status code
      headers: {
        Location: LOGIN_PAGE, // The URL to redirect to
      },
    });
  }
};

export const config = {
  matcher: ["/api/my/:path*", "/my/:path*"],
};
```

In my application, I would like to update the req object within the middleware to include the decrypted session data. This would allow me to access the session data directly in my API routes without the need for the withSessionRoute() wrapper.

Is there a way to enhance the request context to contain the decrypted session data by modifying the middleware function?

I believe this enhancement would provide more flexibility and simplify the usage of the iron-session library in various scenarios. I would appreciate any guidance or suggestions on achieving this.

Thank you for your attention to this matter.

**Comment by brc-dd** [comment] 2023-05-11 16:55
Please avoid creating multiple issues with the same content.

Duplicate of #589

**Closed by brc-dd** 2023-05-11 16:55 UTC
