### ISSUE TITLE
Session is not updating

### ISSUE THREAD

**Issue by aryan-debug** [vvo/iron-session#547] opened 2022-09-23 17:12 UTC
Hi, I have a page where users can give themselves a "role" like member or admin. They can go to another route to create messages. I am trying to update user's role from "user" to "admin". It updates admin role in the `admin.js` file when I log it, but when I go to `messages/create.js` and try to log it, it shows that user still has the "user" role. I am saving the changes I make by calling `req.session.save()` but it is not working.

admin.js
```
import { withIronSessionApiRoute } from "iron-session/next";
import nc from "next-connect";
import { session_config } from "../../lib/config";
import Users from "../../models/user";
import { connectToDatabase } from "../../util/mongodb";

const handler = nc()

handler.post(async (req) => {
    if (req.body.password === process.env.ADMIN_PASSWORD) {
        await connectToDatabase()
        await Users.findOneAndUpdate({ name: req.session.user.name }, { role: "admin" })
        const updated_user = { name: req.session.user.name, role: "admin" }

        req.session.user = updated_user
        await req.session.save()

    }

})

export default withIronSessionApiRoute(handler, session_config);
```

messages/create.js
```
import { withIronSessionApiRoute } from "iron-session/next";
import nc from "next-connect";
import { session_config } from "../../../lib/config";

const handler = nc()
handler.post(async (req) => {
    console.log(req.session.user)
    console.log(req.body)
})

export default withIronSessionApiRoute(handler, session_config)
```

Please let me know what the issue is and how I can fix it. Thank you,

**Comment by aryan-debug** [comment] 2022-10-18 15:23
It's almost been a month. Can someone help me with this issue?

**Comment by dsbrianwebster** [comment] 2022-11-10 23:16
@aryan-debug I can confirm this is happening for me as well

**Comment by petyappetrov** [comment] 2022-12-03 12:09
@aryan-debug update is working, you need to send any response for set cookie

look here how it works
https://github.com/vvo/iron-session/blob/main/src/core.ts#L238

**Comment by aidankinzett** [comment] 2023-04-03 23:42
hi, I am having this same issue. Has this been resolved?

**Comment by dsbrianwebster** [comment] 2023-04-05 00:25
@aidankinzett see [response](https://github.com/vvo/iron-session/issues/547#issuecomment-1336146711) from @petyappetrov. I was having this issue too but it's because i was just saving the session without sending a response. If you do that it update works as expected.

**Comment by aidankinzett** [comment] 2023-04-05 00:28
Yeah thanks, I did end up resolving the issue due to a different typo

**Closed** 2023-11-20 00:56 UTC
